import { jsPDF } from 'jspdf';
import { ExamQuestion } from '../types';

export const downloadQuestionAsPDF = async (question: ExamQuestion, dayNumber?: number) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let currentY = 20;

  // Header
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text('EXAM PREP PRO', margin, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(199, 210, 254); // indigo-200
  doc.setFont('helvetica', 'normal');
  doc.text(`Daily Drill Challenge ${dayNumber ? `- Day ${dayNumber}` : ''}`, margin, 33);
  
  currentY = 55;

  // Question Info Card
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(margin, currentY - 5, contentWidth, 15, 2, 2, 'FD');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text(`${question.paper.toUpperCase()}  |  TOPIC: ${question.topic.toUpperCase()}`, margin + 5, currentY + 5);
  
  currentY += 25;

  // Question Text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('Question:', margin, currentY);
  currentY += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(13);
  doc.setTextColor(51, 65, 85); // slate-700
  const splitText = doc.splitTextToSize(question.questionText, contentWidth);
  doc.text(splitText, margin, currentY);
  currentY += (splitText.length * 7) + 15;

  // Image if exists
  if (question.imageUrl) {
    try {
      const img = new Image();
      img.crossOrigin = 'Anonymous';
      img.src = question.imageUrl;
      
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      const imgWidth = contentWidth;
      const imgHeight = (img.height * imgWidth) / img.width;
      
      // Check if image fits on page, if not add new page
      if (currentY + imgHeight > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        currentY = margin;
      }

      doc.addImage(img, 'JPEG', margin, currentY, imgWidth, imgHeight);
      currentY += imgHeight + 15;
    } catch (error) {
      console.error('Error adding image to PDF:', error);
    }
  }

  // Options if Paper 1
  if (question.paper === 'Paper 1' && question.options) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59); // slate-800
    doc.text('Options:', margin, currentY);
    currentY += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105); // slate-600
    Object.entries(question.options).forEach(([key, value]) => {
      const optionText = `${key}: ${value}`;
      const splitOption = doc.splitTextToSize(optionText, contentWidth - 10);
      
      if (currentY + (splitOption.length * 7) > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        currentY = margin + 10;
      }

      doc.text(splitOption, margin + 5, currentY);
      currentY += (splitOption.length * 7) + 5;
    });
  } else {
    // Space for structured answer
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59); // slate-800
    doc.text('Your Answer:', margin, currentY);
    currentY += 10;

    doc.setDrawColor(226, 232, 240); // slate-200
    doc.rect(margin, currentY, contentWidth, 80);
    currentY += 90;
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Generated by Exam Prep Pro - Your path to an A grade.', margin, footerY);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 30, footerY);

  doc.save(`Question_${question.id || 'export'}.pdf`);
};
